{
  namespace,
  name,
  description,
  packageName ? null,
  namespaceRoot ? "programs",
  optionRoot ? [
    "dragonix"
    "features"
  ],
  ...
}:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  optionPath = optionRoot ++ [ namespaceRoot ] ++ namespace ++ [ name ];
  cfg = lib.getAttrFromPath optionPath config;
  package = if packageName == null then null else lib.attrByPath [ packageName ] null pkgs;
  packageAvailable =
    package != null
    && lib.meta.availableOn pkgs.stdenv.hostPlatform package
    && !lib.elem pkgs.stdenv.hostPlatform.system (package.meta.badPlatforms or [ ]);
  packageDerivation =
    if package == null then { success = false; } else builtins.tryEval package.drvPath;
  hasMainProgram = package != null && (package.meta.mainProgram or null) != null;
  packageExecutable =
    if packageAvailable && packageDerivation.success && hasMainProgram then
      lib.getExe package
    else
      null;
  capabilityId = lib.concatStringsSep "-" ([ namespaceRoot ] ++ namespace ++ [ name ]);
  defaultAliases = lib.optionalAttrs (packageExecutable != null) {
    "dx-${capabilityId}" = packageExecutable;
  };
  configPath = ".config/dragonix-public/${capabilityId}.conf";
  marker = lib.toUpper (
    lib.replaceStrings [ "-" ] [ "_" ] (
      lib.concatStringsSep "_" (
        [
          "DRAGONIX"
          "FEATURE"
          (lib.toUpper namespaceRoot)
        ]
        ++ namespace
        ++ [ name ]
      )
    )
  );
in
{
  options = lib.setAttrByPath optionPath {
    enable = lib.mkEnableOption description;
    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      description = "Additional packages for this public capability.";
    };
    aliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Shell aliases contributed by this public capability.";
    };
    settings = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Portable key-value settings recorded for this capability.";
    };
    environment = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Environment variables contributed by this public capability.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      cfg.extraPackages ++ lib.optional (packageAvailable && packageDerivation.success) package;
    home.shellAliases = defaultAliases // cfg.aliases;
    home.sessionVariables = cfg.environment // {
      ${marker} = "1";
    };
    home.file.${configPath}.text = ''
      # Generated by Dragonix Public. Override this file through the module options.
      capability = ${capabilityId}
      package = ${toString packageName}
      enabled = true
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (key: value: "${key} = ${value}") cfg.settings)}
    '';
  };
}
